/**
 * Region comparison: did the same company show different exit doors to
 * customers in different countries? Reads results/<service>@<region>.json and
 * writes a compliance-style finding to reports/<service>-regions.md.
 *
 *   npm run compare -- <service>
 */
import { writeFile, mkdir } from "node:fs/promises"
import path from "node:path"
import { loadResults } from "./results.js"
import { PATTERN_LABELS } from "./score.js"
import type { PatternType } from "./types.js"

export async function buildRegionReport(service: string): Promise<void> {
  const runs = (await loadResults()).filter((r) => r.service === service && r.region !== "direct")
  if (runs.length < 2) {
    console.error(`Need at least two ${service}@<region>.json results to compare.`)
    return
  }
  runs.sort((a, b) => a.region.localeCompare(b.region))

  const allPatterns = [...new Set(runs.flatMap((r) => r.patterns.map((p) => p.type)))]
  const patternRows = allPatterns.map((type) => {
    const cells = runs.map((r) => (r.patterns.some((p) => p.type === type) ? "yes" : "-"))
    return `| ${PATTERN_LABELS[type as PatternType]} | ${cells.join(" | ")} |`
  })

  const header = `| | ${runs.map((r) => r.region.toUpperCase()).join(" | ")} |`
  const divider = `| --- | ${runs.map(() => "---").join(" | ")} |`
  const metricRows = [
    `| Escape Score | ${runs.map((r) => `${r.score} (${r.grade})`).join(" | ")} |`,
    `| Outcome | ${runs.map((r) => r.outcome).join(" | ")} |`,
    `| Clicks to exit | ${runs.map((r) => r.metrics.clicks).join(" | ")} |`,
    `| Time to exit | ${runs.map((r) => `${Math.round(r.metrics.durationMs / 1000)}s`).join(" | ")} |`,
    `| Dark patterns | ${runs.map((r) => r.patterns.length).join(" | ")} |`,
  ]

  const scores = runs.map((r) => r.score)
  const spread = Math.max(...scores) - Math.min(...scores)
  const easiest = runs.reduce((a, b) => (a.score >= b.score ? a : b))
  const hardest = runs.reduce((a, b) => (a.score <= b.score ? a : b))
  const verdict =
    spread === 0
      ? "The flow was consistent across every region tested."
      : `The exit was measurably easier from ${easiest.region.toUpperCase()} (score ${easiest.score}) than from ${hardest.region.toUpperCase()} (score ${hardest.score}). Customers are not being offered the same door out.`

  const md = `# ${service}: cancellation flow by region

Same service, same account state, same agent. The only variable is the
residential egress country of the browser. Every run has a session replay.

${header}
${divider}
${metricRows.join("\n")}

## Dark patterns encountered

${header}
${divider}
${patternRows.join("\n") || "| (none observed) |" + runs.map(() => " |").join("")}

## Finding

${verdict}

## Evidence

${runs.map((r) => `- ${r.region.toUpperCase()}: session \`${r.sessionId}\`, ${r.ranAt}${r.replayFile ? `, replay \`${r.replayFile}\`` : ""}`).join("\n")}

*Generated by [Hotel California](../README.md). Observations reflect what the
agent was shown on the stated date from the stated egress, on the account
owner's own subscription.*
`
  await mkdir("reports", { recursive: true })
  const out = path.join("reports", `${service}-regions.md`)
  await writeFile(out, md)
  console.log(`region report: ${out} (${runs.length} regions, score spread ${spread})`)
}

const entry = process.argv[1] ?? ""
if (entry.endsWith("compare.ts") || entry.endsWith("compare.js")) {
  const service = process.argv[2]
  if (!service) {
    console.error("Usage: npm run compare -- <service>")
    process.exit(1)
  }
  await buildRegionReport(service)
}
