/**
 * Build LEADERBOARD.md from results/*.json: the Cancellation Difficulty Index,
 * worst offenders first.
 */
import { writeFile } from "node:fs/promises"
import { loadResults } from "./results.js"
import { PATTERN_LABELS } from "./score.js"

export async function buildLeaderboard(): Promise<void> {
  const results = await loadResults()

  const rows = results.map((r) => {
    const patterns =
      r.patterns.length === 0
        ? "-"
        : [...new Set(r.patterns.map((p) => p.type))].join(", ")
    return `| ${r.displayName ?? r.service} | ${r.score} | ${r.grade} | ${r.outcome} | ${r.metrics.clicks} | ${Math.round(r.metrics.durationMs / 1000)}s | ${patterns} |`
  })

  const legend = Object.entries(PATTERN_LABELS)
    .map(([key, label]) => `- \`${key}\`: ${label}`)
    .join("\n")

  const md = `# Cancellation Difficulty Index

Lower score = harder to leave. Scored by an AI agent that attempted the
cancellation itself; every run has an rrweb session replay as the receipt.

| Service | Escape Score | Grade | Outcome | Clicks | Time | Dark patterns observed |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n") || "| (no runs yet) | | | | | | |"}

## Pattern legend

${legend}

*Generated by [Hotel California](README.md). Runs are against the account owner's own subscriptions.*
`
  await writeFile("LEADERBOARD.md", md)
  console.log(`leaderboard: ${results.length} service(s) ranked in LEADERBOARD.md`)
}

const entry = process.argv[1] ?? ""
if (entry.endsWith("report.ts") || entry.endsWith("report.js")) {
  await buildLeaderboard()
}
