/**
 * Build LEADERBOARD.md from results/*.json: the Cancellation Difficulty Index,
 * worst offenders first.
 */
import { readFile, readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { PATTERN_LABELS } from "./score.js"
import type { RunResult } from "./types.js"

export async function buildLeaderboard(): Promise<void> {
  let files: string[]
  try {
    files = (await readdir("results")).filter((f) => f.endsWith(".json"))
  } catch {
    files = []
  }
  const results: RunResult[] = []
  for (const f of files) {
    results.push(JSON.parse(await readFile(path.join("results", f), "utf8")) as RunResult)
  }
  results.sort((a, b) => a.score - b.score)

  const rows = results.map((r) => {
    const patterns =
      r.patterns.length === 0
        ? "-"
        : [...new Set(r.patterns.map((p) => p.type))].join(", ")
    return `| ${r.service} | ${r.score} | ${r.grade} | ${r.outcome} | ${r.metrics.clicks} | ${Math.round(r.metrics.durationMs / 1000)}s | ${patterns} |`
  })

  const legend = Object.entries(PATTERN_LABELS)
    .map(([key, label]) => `- \`${key}\`: ${label}`)
    .join("\n")

  const md = `# Cancellation Difficulty Index

Lower score = harder to leave. Scored by an AI agent that attempted the
cancellation itself; every run has an rrweb session replay as the receipt.

| Service | Escape Score | Grade | Outcome | Clicks | Time | Dark patterns observed |
| --- | --- | --- | --- | --- | --- | --- |
${rows.join("\n") || "| (no runs yet) | | | | | | |"}

## Pattern legend

${legend}

*Generated by [Hotel California](README.md). Runs are against the account owner's own subscriptions.*
`
  await writeFile("LEADERBOARD.md", md)
  console.log(`leaderboard: ${results.length} service(s) ranked in LEADERBOARD.md`)
}

const entry = process.argv[1] ?? ""
if (entry.endsWith("report.ts") || entry.endsWith("report.js")) {
  await buildLeaderboard()
}
